using System;
using System.Collections.Generic;
using System.Text;

namespace BlockbusterLab
{
    class ConsoleFormatter
    {
        // ============================================================================================================================
        // Formatting Methods: Provides common functionality for most input-oriented console applications

        // Prompts user for an input, with the message parameter serving as context. Returns the string generated by the user's input.
        // Does not allow blank inputs, and will repeat until an input is given.
        public static string PromptForInput(string message)
        {
            while (true)
            {
                Console.Write(message);
                string userInput = (Console.ReadLine()).Trim();
                if (userInput.Length > 0)
                {
                    return userInput;
                }
            }
        }

        // Prompts user if they want to continue using the program or a program functionality. 
        // If yes, then let the loop iterate. Otherwise, stop the loop by setting done to true.
        public static bool AskToContinue(string message)
        {
            while (true)
            {
                string promptMsg = message + " (y/n) ";
                string inputStr = PromptForInput(promptMsg);
                inputStr = inputStr.Trim().ToLower();
                if (inputStr.Equals("y"))
                {
                    return false;
                }
                else if (inputStr.Equals("n"))
                {
                    return true;
                }
                else
                {
                    Console.WriteLine($"Error: Please input y/Y or n/N.");
                }
            }
        }

        // Stops program until user inputs a keystroke
        public static void PauseByAnyKey()
        {
            Console.WriteLine("Press any Key to continue...");
            Console.ReadKey();
            Console.Clear();
        }

        // Adds empty lines in console for formatting
        public static void MakeLineSpace(int x)
        {
            for (int i = 0; i < x; i++)
            {
                Console.WriteLine(" ");
            }
        }
    }
}
